import { useState, useEffect } from 'react';
import { useSearchParams, Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ArrowLeft, Download, Share2, CheckCircle, XCircle,
  Lightbulb, Target, BarChart2, FileText, AlertTriangle, Zap
} from 'lucide-react';
import { getResumeById, getResumes, StoredResume } from '../services/resumeStore';
import { getScoreLabel } from '../services/atsAnalyzer';
import ScoreCircle from '../components/ScoreCircle';
import ProgressBar from '../components/ProgressBar';
import SkillBadge from '../components/SkillBadge';
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip } from 'recharts';
import toast from 'react-hot-toast';

export default function ResultsPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const resumeId = searchParams.get('id');
  const [resume, setResume] = useState<StoredResume | null>(null);
  const [activeTab, setActiveTab] = useState<'overview' | 'skills' | 'suggestions' | 'keywords'>('overview');

  useEffect(() => {
    if (resumeId) {
      const found = getResumeById(resumeId);
      setResume(found ?? null);
    } else {
      // Load first complete resume
      const all = getResumes();
      const first = all.find(r => r.status === 'complete' && r.analysis);
      setResume(first ?? null);
    }
  }, [resumeId]);

  if (!resume || !resume.analysis) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 rounded-2xl bg-indigo-50 flex items-center justify-center mx-auto mb-4">
            <FileText size={28} className="text-indigo-400" />
          </div>
          <p className="text-gray-600 font-medium">No analysis found</p>
          <Link to="/upload" className="mt-4 inline-block text-sm text-indigo-600 font-medium hover:underline">
            Upload a resume →
          </Link>
        </div>
      </div>
    );
  }

  const { analysis } = resume;
  const { label, color, bg } = getScoreLabel(analysis.atsScore);

  const radarData = [
    { subject: 'Format', value: analysis.formatScore },
    { subject: 'Keywords', value: analysis.keywordScore },
    { subject: 'Experience', value: analysis.experienceScore },
    { subject: 'Readability', value: analysis.readabilityScore },
    { subject: 'ATS Score', value: analysis.atsScore },
  ];

  const handleExport = () => {
    const reportContent = `
ResumeIQ — ATS Analysis Report
================================
File: ${resume.fileName}
Date: ${new Date().toLocaleDateString()}

ATS SCORE: ${analysis.atsScore}/100 (${label})
Format Score: ${analysis.formatScore}/100
Keyword Score: ${analysis.keywordScore}/100
Experience Score: ${analysis.experienceScore}/100
Readability Score: ${analysis.readabilityScore}/100

SKILLS FOUND (${analysis.skillsFound.length}):
${analysis.skillsFound.join(', ')}

MISSING SKILLS (${analysis.missingSkills.length}):
${analysis.missingSkills.join(', ') || 'None'}

STRENGTHS:
${analysis.strengths.map(s => `• ${s}`).join('\n')}

AREAS TO IMPROVE:
${analysis.weaknesses.map(w => `• ${w}`).join('\n')}

IMPROVEMENT SUGGESTIONS:
${analysis.suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Sections Detected:
${Object.entries(analysis.sections).map(([k, v]) => `• ${k}: ${v ? '✓' : '✗'}`).join('\n')}

Generated by ResumeIQ — resumeiq.app
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ResumeIQ_Report_${resume.fileName.replace(/\.[^.]+$/, '')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('ATS Report exported! 📄');
  };

  const TABS = [
    { id: 'overview', label: 'Overview', icon: BarChart2 },
    { id: 'skills', label: 'Skills', icon: Target },
    { id: 'suggestions', label: 'Suggestions', icon: Lightbulb },
    { id: 'keywords', label: 'Keywords', icon: Zap },
  ] as const;

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8"
        >
          <div className="flex items-center gap-3">
            <button onClick={() => navigate('/dashboard')} className="p-2 rounded-xl hover:bg-white border border-transparent hover:border-gray-200 text-gray-500 hover:text-gray-700 transition-all">
              <ArrowLeft size={18} />
            </button>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">ATS Analysis Results</h1>
              <p className="text-sm text-gray-400 mt-0.5 flex items-center gap-1.5">
                <FileText size={12} />
                {resume.fileName}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => { navigator.clipboard.writeText(window.location.href); toast.success('Link copied!'); }}
              className="flex items-center gap-2 px-4 py-2 text-sm border border-gray-200 text-gray-600 rounded-xl hover:bg-white transition-all"
            >
              <Share2 size={14} />
              Share
            </button>
            <button
              onClick={handleExport}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-all"
            >
              <Download size={14} />
              Export Report
            </button>
          </div>
        </motion.div>

        {/* Score Hero Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-2xl p-6 sm:p-8 shadow-sm border border-gray-100 mb-6"
        >
          <div className="flex flex-col sm:flex-row items-center sm:items-start gap-8">
            {/* Big Score Circle */}
            <div className="flex flex-col items-center gap-2">
              <ScoreCircle score={analysis.atsScore} size={140} strokeWidth={12} />
              <span className={`text-xs font-semibold px-3 py-1 rounded-full ${bg} ${color}`}>
                ATS Score
              </span>
            </div>

            {/* Score Details */}
            <div className="flex-1 w-full">
              <div className="flex items-center gap-2 mb-2">
                <span className={`text-lg font-bold ${color}`}>{label}</span>
                <span className="text-gray-300">•</span>
                <span className="text-sm text-gray-500">{analysis.wordCount} words</span>
                <span className="text-gray-300">•</span>
                <span className="text-sm text-gray-500">{analysis.skillsFound.length} skills detected</span>
              </div>
              <h2 className="text-2xl font-extrabold text-gray-900 mb-4">
                {analysis.atsScore >= 80 ? 'Your resume is ATS-ready! 🚀' :
                 analysis.atsScore >= 65 ? 'Good resume with room to improve 📈' :
                 analysis.atsScore >= 45 ? 'Your resume needs optimization 🛠️' :
                 'Resume needs significant improvements ⚠️'}
              </h2>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: 'Format', value: analysis.formatScore },
                  { label: 'Keywords', value: analysis.keywordScore },
                  { label: 'Experience', value: analysis.experienceScore },
                  { label: 'Readability', value: analysis.readabilityScore },
                ].map(item => {
                  const { color: c } = getScoreLabel(item.value);
                  return (
                    <div key={item.label} className="bg-gray-50 rounded-xl p-3 text-center">
                      <p className={`text-2xl font-bold ${c}`}>{item.value}</p>
                      <p className="text-xs text-gray-500 mt-0.5">{item.label}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Tabs */}
        <div className="flex gap-1 bg-white rounded-xl p-1 border border-gray-100 shadow-sm mb-6 overflow-x-auto">
          {TABS.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all whitespace-nowrap flex-1 justify-center ${
                activeTab === tab.id
                  ? 'bg-indigo-600 text-white shadow-sm'
                  : 'text-gray-600 hover:bg-gray-50'
              }`}
            >
              <tab.icon size={14} />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.2 }}
        >
          {activeTab === 'overview' && (
            <div className="grid lg:grid-cols-2 gap-6">
              {/* Radar Chart */}
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h3 className="font-semibold text-gray-800 mb-4">Performance Radar</h3>
                <ResponsiveContainer width="100%" height={240}>
                  <RadarChart data={radarData}>
                    <PolarGrid stroke="#f1f5f9" />
                    <PolarAngleAxis dataKey="subject" tick={{ fontSize: 11, fill: '#94a3b8' }} />
                    <Radar name="Score" dataKey="value" stroke="#6366f1" fill="#6366f1" fillOpacity={0.15} strokeWidth={2} />
                    <Tooltip contentStyle={{ borderRadius: 10, border: '1px solid #e2e8f0' }} />
                  </RadarChart>
                </ResponsiveContainer>
              </div>

              {/* Sections & Strengths/Weaknesses */}
              <div className="space-y-4">
                {/* Sections */}
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                  <h3 className="font-semibold text-gray-800 mb-3">Resume Sections</h3>
                  <div className="grid grid-cols-2 gap-2">
                    {Object.entries(analysis.sections).map(([key, val]) => (
                      <div key={key} className={`flex items-center gap-2 p-2.5 rounded-lg text-xs font-medium ${val ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-600'}`}>
                        {val ? <CheckCircle size={13} /> : <XCircle size={13} />}
                        <span className="capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Score Bars */}
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                  <h3 className="font-semibold text-gray-800 mb-4">Score Breakdown</h3>
                  <div className="space-y-3">
                    <ProgressBar label="Format Score" value={analysis.formatScore} delay={0.1} />
                    <ProgressBar label="Keyword Score" value={analysis.keywordScore} delay={0.2} />
                    <ProgressBar label="Experience Score" value={analysis.experienceScore} delay={0.3} />
                    <ProgressBar label="Readability Score" value={analysis.readabilityScore} delay={0.4} />
                  </div>
                </div>
              </div>

              {/* Strengths */}
              {analysis.strengths.length > 0 && (
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                  <div className="flex items-center gap-2 mb-3">
                    <CheckCircle size={16} className="text-emerald-500" />
                    <h3 className="font-semibold text-gray-800">Strengths</h3>
                  </div>
                  <ul className="space-y-2">
                    {analysis.strengths.map((s, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-gray-700">
                        <span className="text-emerald-500 mt-0.5">✓</span>
                        {s}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Weaknesses */}
              {analysis.weaknesses.length > 0 && (
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                  <div className="flex items-center gap-2 mb-3">
                    <AlertTriangle size={16} className="text-amber-500" />
                    <h3 className="font-semibold text-gray-800">Areas to Improve</h3>
                  </div>
                  <ul className="space-y-2">
                    {analysis.weaknesses.map((w, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-gray-700">
                        <span className="text-amber-500 mt-0.5">⚠</span>
                        {w}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {activeTab === 'skills' && (
            <div className="grid lg:grid-cols-2 gap-6">
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <div className="flex items-center gap-2 mb-4">
                  <CheckCircle size={16} className="text-emerald-500" />
                  <h3 className="font-semibold text-gray-800">Skills Found ({analysis.skillsFound.length})</h3>
                </div>
                <div className="flex flex-wrap gap-2">
                  {analysis.skillsFound.map(skill => (
                    <SkillBadge key={skill} skill={skill} variant="found" size="md" />
                  ))}
                  {analysis.skillsFound.length === 0 && (
                    <p className="text-sm text-gray-400">No recognized skills detected. Try expanding your skills section.</p>
                  )}
                </div>
              </div>

              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <div className="flex items-center gap-2 mb-4">
                  <XCircle size={16} className="text-red-500" />
                  <h3 className="font-semibold text-gray-800">Common Missing Skills</h3>
                </div>
                {analysis.missingSkills.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {analysis.missingSkills.map(skill => (
                      <SkillBadge key={skill} skill={skill} variant="missing" size="md" />
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-6">
                    <span className="text-3xl">🎉</span>
                    <p className="text-sm text-emerald-600 font-medium mt-2">No critical missing skills!</p>
                    <p className="text-xs text-gray-400 mt-1">Try matching with a specific job description for targeted results.</p>
                  </div>
                )}
                <div className="mt-4 pt-4 border-t border-gray-50">
                  <Link
                    to={`/job-match?resumeId=${resume.id}`}
                    className="flex items-center justify-center gap-2 py-2.5 text-sm font-medium text-indigo-600 bg-indigo-50 rounded-xl hover:bg-indigo-100 transition-colors"
                  >
                    <Zap size={14} />
                    Match with a job description for precise gaps
                  </Link>
                </div>
              </div>

              {/* Skill progress bars */}
              <div className="lg:col-span-2 bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h3 className="font-semibold text-gray-800 mb-4">Skill Category Coverage</h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  {[
                    { label: 'Frontend Technologies', skills: ['React', 'Vue', 'Angular', 'TypeScript', 'HTML', 'CSS'], value: 0 },
                    { label: 'Backend Technologies', skills: ['Node.js', 'Python', 'Express', 'Java', 'Go'], value: 0 },
                    { label: 'DevOps & Cloud', skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD', 'GitHub Actions'], value: 0 },
                    { label: 'Databases', skills: ['PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'SQL'], value: 0 },
                  ].map(cat => {
                    const found = cat.skills.filter(s => analysis.skillsFound.map(x => x.toLowerCase()).includes(s.toLowerCase()));
                    const pct = Math.round((found.length / cat.skills.length) * 100);
                    return (
                      <div key={cat.label}>
                        <div className="flex items-center justify-between mb-1.5">
                          <span className="text-sm font-medium text-gray-700">{cat.label}</span>
                          <span className="text-xs text-gray-400">{found.length}/{cat.skills.length}</span>
                        </div>
                        <ProgressBar label="" value={pct} showValue={false} delay={0.1} />
                        <div className="flex flex-wrap gap-1 mt-1.5">
                          {cat.skills.slice(0, 5).map(s => {
                            const isFound = analysis.skillsFound.map(x => x.toLowerCase()).includes(s.toLowerCase());
                            return (
                              <span key={s} className={`text-[9px] px-1.5 py-0.5 rounded font-medium ${isFound ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-400'}`}>
                                {s}
                              </span>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          )}

          {activeTab === 'suggestions' && (
            <div className="space-y-4">
              <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
                <div className="flex items-center gap-2 mb-1">
                  <Lightbulb size={16} className="text-amber-600" />
                  <h3 className="font-semibold text-amber-800">AI-Powered Suggestions</h3>
                </div>
                <p className="text-sm text-amber-700">Follow these personalized recommendations to boost your ATS score and get more callbacks.</p>
              </div>

              <div className="grid gap-3">
                {analysis.suggestions.map((suggestion, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 flex items-start gap-4"
                  >
                    <div className="w-8 h-8 rounded-xl bg-indigo-50 flex items-center justify-center flex-shrink-0 text-indigo-700 font-bold text-sm">
                      {i + 1}
                    </div>
                    <div className="flex-1">
                      <p className="text-sm text-gray-700 leading-relaxed">{suggestion}</p>
                    </div>
                    <span className={`flex-shrink-0 text-[10px] font-bold px-2 py-1 rounded-full ${
                      i < 2 ? 'bg-red-100 text-red-600' :
                      i < 4 ? 'bg-amber-100 text-amber-600' :
                      'bg-green-100 text-green-600'
                    }`}>
                      {i < 2 ? 'HIGH' : i < 4 ? 'MED' : 'LOW'}
                    </span>
                  </motion.div>
                ))}
              </div>

              {/* CTA to job match */}
              <div className="bg-gradient-to-br from-indigo-600 to-purple-700 rounded-2xl p-6 text-center text-white">
                <Zap size={24} className="mx-auto mb-3 text-indigo-200" />
                <h3 className="font-bold text-lg">Get Job-Specific Suggestions</h3>
                <p className="text-indigo-200 text-sm mt-2">Paste a job description to discover exactly what skills to add.</p>
                <Link
                  to={`/job-match?resumeId=${resume.id}`}
                  className="mt-4 inline-flex items-center gap-2 px-5 py-2.5 bg-white text-indigo-700 font-semibold rounded-xl hover:bg-indigo-50 transition-all text-sm"
                >
                  Match with Job Description →
                </Link>
              </div>
            </div>
          )}

          {activeTab === 'keywords' && (
            <div className="grid lg:grid-cols-2 gap-6">
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
                <h3 className="font-semibold text-gray-800 mb-4">Top Keywords</h3>
                <div className="space-y-3">
                  {analysis.keywords.slice(0, 12).map((kw, i) => (
                    <div key={kw.word} className="flex items-center gap-3">
                      <span className="text-xs text-gray-400 w-4 text-right">{i + 1}</span>
                      <div className="flex-1">
                        <div className="flex items-center justify-between mb-1">
                          <span className={`text-sm font-medium capitalize ${kw.important ? 'text-indigo-700' : 'text-gray-700'}`}>
                            {kw.word}
                            {kw.important && <span className="ml-1.5 text-[9px] bg-indigo-100 text-indigo-600 px-1.5 py-0.5 rounded-full font-semibold">KEY</span>}
                          </span>
                          <span className="text-xs text-gray-400">×{kw.count}</span>
                        </div>
                        <div className="h-1.5 bg-gray-100 rounded-full">
                          <div
                            className={`h-1.5 rounded-full ${kw.important ? 'bg-indigo-500' : 'bg-gray-300'}`}
                            style={{ width: `${Math.min(100, (kw.count / (analysis.keywords[0]?.count || 1)) * 100)}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                  {analysis.keywords.length === 0 && (
                    <p className="text-sm text-gray-400 text-center py-4">No repeated keywords found. Add more relevant terms.</p>
                  )}
                </div>
              </div>

              <div className="space-y-4">
                <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                  <h3 className="font-semibold text-gray-800 mb-3">Keyword Health</h3>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                      <span className="text-sm text-gray-600">Total unique keywords</span>
                      <span className="font-bold text-gray-800">{analysis.keywords.length}</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                      <span className="text-sm text-gray-600">Technical keywords</span>
                      <span className="font-bold text-indigo-600">{analysis.keywords.filter(k => k.important).length}</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                      <span className="text-sm text-gray-600">Word count</span>
                      <span className="font-bold text-gray-800">{analysis.wordCount}</span>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                      <span className="text-sm text-gray-600">Keyword density</span>
                      <span className="font-bold text-emerald-600">
                        {((analysis.skillsFound.length / Math.max(analysis.wordCount, 1)) * 100).toFixed(1)}%
                      </span>
                    </div>
                  </div>
                </div>

                <div className="bg-indigo-50 border border-indigo-100 rounded-2xl p-5">
                  <h3 className="font-semibold text-indigo-800 mb-2">💡 Keyword Tips</h3>
                  <ul className="space-y-2 text-xs text-indigo-700">
                    <li>• Aim for 2-3% keyword density for optimal ATS scoring</li>
                    <li>• Use exact phrases from the job description</li>
                    <li>• Include both acronyms and full names (e.g., "CI/CD" and "Continuous Integration")</li>
                    <li>• Place key skills in your summary section for higher weight</li>
                  </ul>
                </div>
              </div>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
}
